### ISSUE TITLE
Some problems with discover

### ISSUE THREAD

**Issue by iDeaDe** [moppletop/YeeLight-API#6]
JDK: BellSoft Liberica JDK 17.0.7 (build 17.0.7+7-LTS)
OS: Manjaro 23.0.1

Hi, I'm writing an application to control light bulbs from PC.
I encountered this problem: In com.moppletop.yeelight.api.discovery.DiscoveryUDPListener on line 105 there is a socket connection creation, and there is a method InetAddress.getLocalHost() which, according to your comment should return the address of the current device in the local network. In my case this method returns the address 127.0.1.1, so socket.receive() on line 80 does not get any information about the current available devices. Perhaps we should put the address passed to the constructor into the parameters (YeeConfiguration class)? In my case, passing null as the address works, but the method is private and the class is buried deep in the code, so I don't see any way to change this behavior

**Comment by moppletop** [comment]
Hello,
I've made a change to allow you to customise the discovery bind address from the YeeConfiguration within the YeeApiBuilder. Let me know if that solves your problem.

**Comment by iDeaDe** [comment]
Yeah, thanks, that's just what I needed.
